version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: echobot-front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - chat-network-prod

networks:
  chat-network-prod:
    driver: bridge